name: Development distribution

on:
  push:
    branch: develop

    pull_request: develop

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      db:
        env:
          POSTGRES_USER: 'postgres'
          POSTGRES_PASSWORD: 'postgres'
        image: postgres:9.6
        ports: ['5432:5432']
        options: >-
          --health-cmd pg_isready
          --health-interval 30s
          --health-timeout 30s
          --health-retries 200

    steps:
      - uses: actions/checkout@v1

      - name: Set up Node 12.x
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Get yarn cache dir
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install libraries
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client
      - name: Creating database
        env:
          POSTGRES_PASSWORD: 'postgres'
          PGPASSWORD: 'postgres'
        run: |
          echo "Creating Postgres Database"
          psql -h localhost -c 'create database "a-companies-test";' -U postgres
      - name: Build
        run: |
          yarn install
      - name: Set up database for tests
        run: |
          yarn run migration:run
        env:
          NODE_ENV: test

      - name: Run tests
        run: yarn test
        env:
          NODE_ENV: test
          PGHOST: localhost
          PGPORT: 5432
          PGDATABASE: pokegraph
          PGUSER: postgres
          PGPASSWORD: postgres

        